### ISSUE TITLE
Polling stops working after some time

### ISSUE THREAD

**Issue by timcharper** [timcharper/homebridge-opensprinkler#1]
Seems like the HTTP request will get stuck and never time out

**Comment by calanish** [comment]
This seems to be a feature with HomeBridge, usually tapping the updating icon seems to update it. 

PS the plugin does just seem to work though:)

**Comment by timcharper** [comment]
I refactored the logic to make it more sound (used promises, made sure to catch my exceptions, etc); I haven't seen the problem resurface since and it's been more reliable.
