### ISSUE TITLE
Port # Issue: The requested URL /ja was not found on this server

### ISSUE THREAD

**Issue by titioft** [timcharper/homebridge-opensprinkler#4]
I cannot specify port 8080 (which is the default for opensprinkler) in the address field in config.json file of homebridge if I do I get parsing error if I don't I get requested URL not found...

How can I specify the port address?

**Comment by calanish** [comment]
Here is my config.json - apologies for formatting, password has been changed obviously.

```json
 {
                        "platform": "OpenSprinkler",
                        "host": "ospi.lan:8080",
                        "password": {
                                "plain": "letmeout!"
                        },
                        "enabledStationIds": [0, 1, 2, 3],
                        "defaultDurationSecs": 600,
                        "pollIntervalMs": 5000
                },
```

**Comment by timcharper** [comment]
Putting a port in the `host` field works just fine for me. Please provide the full error message you are seeing.

**Comment by timcharper** [comment]
Closing as can't reproduce. Will re-open if you provide substantial evidence there is an actual bug here.
