### ISSUE TITLE
Promise.finally

### ISSUE THREAD

**Issue by gamma** [timcharper/homebridge-opensprinkler#5]
I'm having trouble with the promise API. There are two calls to finally in system.js - they produce "not a function" errors.

    /homebridge # node --version
    v8.11.1

Changing them to `then` solves the problem, but I'm not sure if this is an intended way ...

**Comment by timcharper** [comment]
@gamma Hmm, sounds like maybe I should bring in the polyfill. I had read 8.1.4 introduced it but apparently it is only enabled with a flag in that version.

**Comment by timcharper** [comment]
Can you give 0.2.1 a shot @gamma and let me know if this fixes it for you?

**Comment by gamma** [comment]
0.2.1 works for me thanks a lot!
